import { englishCount, formatIntegerForLocale, type Catalog } from './catalog';

export const en = {
  metadata: {
    title: 'DeskGraph — Pre-release',
    description: 'DeskGraph pre-release local-first computer context graph',
  },
  language: {
    selectorLabel: 'Display language',
  },
  hero: {
    eyebrow: 'DeskGraph · M2 Local Context',
    heading: 'Graphify your computer.',
    description:
      'Authorize one local folder at a time, build its metadata manifest, and keep bounded text extraction on this computer—without uploading paths or content.',
    release: 'PRE-RELEASE',
  },
  loading: {
    heading: 'Opening the local manifest',
    description: 'No authorized folder is scanned automatically.',
  },
  backendError: {
    heading: 'Local manifest unavailable',
    description: 'The backend returned no validated status. Raw local errors and paths are hidden.',
    retry: 'Retry',
  },
  runtime: {
    kicker: 'Local runtime',
    heading: 'Manifest is ready',
    localOnly: 'Local only',
    platform: 'Platform',
    sqliteManifest: 'SQLite manifest',
    optionalLocalLlm: 'Optional local LLM',
    networkRequired: 'Network required',
    ready: 'Ready',
    no: 'No',
    lifecycle: { notInitialized: 'Not initialized', disabled: 'Disabled' },
  },
  manifest: {
    kicker: 'Current graph',
    emptyHeading: 'Nothing indexed yet',
    readyHeading: 'Metadata indexed',
    files: 'Files',
    folders: 'Folders',
    locations: 'Locations',
    scanIssues: 'Scan issues',
  },
  search: {
    kicker: 'Deterministic local search',
    heading: 'Find filenames and extracted text',
    description:
      'Traditional Chinese and English queries stay inside SQLite. Embeddings are off; every result says which local field matched.',
    mode: 'Lexical · offline',
    queryLabel: 'Search local context',
    queryPlaceholder: '專案脈絡 or project context',
    scopeAria: 'Search folder scope',
    allFolders: 'All authorized folders',
    authorizedScope: (scopeId) => `Authorized scope ${scopeId}`,
    search: 'Search',
    searching: 'Searching…',
    filtersAria: 'Bounded local search filters',
    sourceLabel: 'Match source',
    sources: {
      all: 'Paths + extracted text',
      paths: 'Filenames and paths only',
      extractedText: 'Extracted text only',
    },
    fileType: 'File type',
    fileTypePlaceholder: 'md or pdf',
    modifiedSince: 'Modified since (UTC)',
    modifiedBefore: 'Before (UTC, exclusive)',
    validation: {
      query: 'Enter at least 3 characters to keep local search bounded.',
      extension: 'File type must be a 1–16 character extension such as md, pdf, or docx.',
      dateRange: 'Choose a valid UTC date range where “Modified since” is before “Before”.',
      request: 'Search stopped safely. Try a shorter query or refresh the local manifest.',
    },
    empty: (query) => `No current path or active extracted text matched “${query}”.`,
    summary: (count, elapsedMs) =>
      `${englishCount(count, 'result')} · ${formatIntegerForLocale(elapsedMs, 'en')} ms`,
    filters: {
      scope: (scopeId) => `scope ${scopeId}`,
      pathsOnly: 'paths only',
      textOnly: 'extracted text only',
      since: (date) => `since ${date} UTC`,
      before: (date) => `before ${date} UTC`,
      allSources: 'all authorized local sources',
    },
    explanation: {
      filenameAndText: 'Exact filename + extracted text',
      filename: 'Exact filename',
      pathAndText: 'Path + extracted text',
      path: 'Filename or path',
      text: 'Extracted text',
    },
    ocr: {
      controlsAria: 'Local screenshot OCR controls',
      notRead: 'Screenshot text has not been read',
      description: 'Only this already-scanned screenshot is revalidated and read on this computer.',
      cancel: 'Cancel OCR',
      stopping: 'Stopping safely…',
      retryQueued: 'Retry queued OCR',
      resume: 'Resume screenshot OCR',
      readAgain: 'Read screenshot again',
      read: 'Read screenshot text locally',
      untrustedText: 'Untrusted local text',
      queued: 'Waiting to start',
      running: 'Extracting bounded text…',
      reading: 'Reading screenshot text locally…',
      completed: 'Screenshot text indexed locally',
      cancelled: 'Cancelled safely',
      interrupted: 'Interrupted safely',
      unavailable: 'Screenshot OCR unavailable or skipped safely',
      skipped: 'File skipped safely',
      capacity: 'Another local OCR is still finishing. This job remains queued; retry it safely.',
      providerUnavailable:
        'Screenshot OCR stopped safely. The local provider may be unavailable on this computer.',
      indexed: 'Screenshot text was indexed locally. Search again to find its contents.',
      cancelledFeedback: 'Screenshot OCR was cancelled safely. No partial text was published.',
      interruptedFeedback: 'Screenshot OCR was interrupted safely. Resume it to continue locally.',
      failedFeedback:
        'Screenshot OCR stopped safely. The previous complete local index was preserved.',
      denied:
        'OCR was denied safely. Rescan the file if it changed and confirm it is a supported screenshot.',
      resumeDenied: 'Resume was denied safely. Refresh the local manifest before trying again.',
      cancelDenied: 'The cancellation request could not be recorded safely.',
    },
  },
  actions: {
    kicker: 'Safe organization preview',
    heading: 'Review a rename without changing the file',
    description:
      'DeskGraph revalidates the selected scope, current manifest snapshot, file identity, read-only open handle, proposed name, and destination before it journals a preview.',
    previewOnly: 'Preview only · no execute',
    folderLabel: 'Authorized folder',
    chooseFolder: 'Choose a scanned folder',
    scopeOption: (scopeId, path) => `Scope ${scopeId} · ${path}`,
    sourceLabel: 'Current absolute file path',
    sourcePlaceholder: '/authorized/folder/draft.md',
    newNameLabel: 'Proposed filename only',
    newNamePlaceholder: 'final.md',
    validating: 'Validating safely…',
    createPreview: 'Create durable preview',
    validation: {
      chooseFolder: 'Choose the authorized folder first.',
      required: 'Enter the current absolute file path and one proposed filename.',
      denied:
        'Preview denied safely. Rescan a changed file, verify the authorized folder, and choose an unused portable filename.',
    },
    previewAria: 'Validated rename preview',
    plan: (planId) => `Plan ${planId} · validated preview`,
    caseOnly: 'Case-only rename requires a staged future executor.',
    direct: 'Direct rename strategy recorded for a future executor.',
    unchanged: 'No file changed',
    before: 'Before',
    after: 'After',
    policyAria: 'Passed policy checks',
    policy: {
      authorizedScope: 'Inside the selected authorized folder',
      manifestFile: 'Current scanned file',
      canonicalSource: 'Canonical source stays in scope',
      sourceIdentity: 'Platform identity matches the manifest',
      readOnlyHandle: 'Read-only open handle matches',
      portableName: 'Portable one-part filename',
      sameParent: 'Same canonical parent folder',
      destinationScope: 'Destination stays in scope',
      destinationAvailable: 'Destination is available',
    },
    noExecute:
      'This plan is journaled but cannot execute. Recovery and Undo do not exist yet, so DeskGraph exposes no action button.',
    historyHeading: 'Recent path-free preview history',
    plans: (count) => englishCount(count, 'plan'),
    historyEmpty:
      'No organization preview has been journaled. Files cannot be changed from this app.',
    historyPlan: (planId) => `Rename preview ${planId}`,
    historyScopeNode: (scopeId, nodeId) => `Scope ${scopeId} · node ${nodeId}`,
    caseOnlyStaged: 'Case-only staged',
    directPreviewed: 'Direct · previewed',
  },
  watch: {
    kicker: 'Native event hints with safety reconciliation',
    heading: 'Native event hints + 5-minute safety reconciliation',
    description:
      'Native filesystem events are hints only. A five-minute periodic safety reconciliation also checks eligible, previously scanned folders in bounded batches. It does not promise incremental content refresh or a completion deadline.',
    adapterActive: 'Native hints + 5-minute safety reconciliation · active',
    adapterStarting: 'Native hints + 5-minute safety reconciliation · starting',
    adapterDegraded: 'Native hints or periodic-only fallback · needs attention',
    adapterStopped: 'Native hints + 5-minute safety reconciliation · stopped',
    metrics: {
      recent: 'Recent events',
      observed: 'Observed hints',
      reconciled: 'Reconciled',
      deferred: 'Deferred folders',
      attention: 'Needs attention',
    },
    empty:
      'No changes observed yet. Due, previously scanned folders are scheduled locally in bounded batches; newly authorized folders still require an explicit initial scan.',
    status: {
      stabilizing: 'Waiting for a stable snapshot',
      reconciling: 'Atomic manifest reconciliation',
      completed: 'Reconciled',
      noFailure: 'No failure',
    },
    reason: {
      temporary: 'Temporary download ignored',
      hidden: 'Hidden entry ignored',
      unsupported: 'Unsupported entry ignored',
      unavailable: 'Source unavailable',
      failed: 'Reconciliation failed safely',
    },
    event: (eventId, scopeId, hints) =>
      `Event ${eventId} · scope ${scopeId} · ${formatIntegerForLocale(hints, 'en')} coalesced hint${hints === 1 ? '' : 's'}`,
    scan: (jobId) => `Scan ${jobId}`,
    noScan: 'No scan yet',
  },
  extraction: {
    kicker: 'Bounded local content',
    emptyHeading: 'No file content extracted yet',
    readyHeading: 'Local text is ready',
    description:
      'Only already-scanned supported documents and explicitly selected screenshots are eligible. Every source is revalidated, output is size-limited, and a failed job cannot replace the last complete text.',
    neverUploaded: 'Never uploaded',
    metrics: {
      files: 'Files with text',
      chunks: 'Active chunks',
      completed: 'Completed jobs',
      skipped: 'Skipped or cancelled',
    },
    latest: (operation, jobId) => `Latest ${operation} job ${jobId}`,
    operation: { screenshotOcr: 'Screenshot OCR', content: 'content' },
    progress: (chunks, bytes) =>
      `${englishCount(chunks, 'chunk')} · ${englishCount(bytes, 'byte')}`,
    optInEmpty: 'Extraction is opt-in. Authorizing or scanning a folder never reads file contents.',
  },
  scope: {
    kicker: 'Explicit authorization',
    heading: 'Folders DeskGraph may inspect',
    description:
      'Enter an existing folder path. Authorization and scanning are separate actions; symlinks and hidden entries are not followed.',
    count: (count) => `${formatIntegerForLocale(count, 'en')} authorized`,
    inputLabel: 'Folder path',
    placeholder: '/Users/you/Documents or C:\\Users\\you\\Documents',
    authorize: 'Authorize folder',
    emptyHeading: 'No folder access',
    emptyDescription: 'DeskGraph cannot inspect Desktop, Downloads, or Documents until added here.',
    label: (scopeId) => `Authorized scope ${scopeId}`,
    progress: (processed, queued, issues) =>
      `${formatIntegerForLocale(processed, 'en')} / ${englishCount(queued, 'entry')} · ${englishCount(issues, 'issue')}`,
    pause: 'Pause scan',
    pausing: 'Pausing…',
    resume: 'Resume scan',
    scan: 'Scan metadata',
    validation: {
      required: 'Enter an existing folder path first.',
      validating: 'Validating the folder boundary…',
      authorized: 'Folder authorized. Nothing was scanned until you choose Scan metadata.',
      denied: 'The folder could not be authorized. Check that it exists and is not protected.',
      reading: 'Reading metadata inside the authorized folder…',
      complete: (files, folders) =>
        `Scan complete: ${englishCount(files, 'file')} and ${englishCount(folders, 'folder')}.`,
      paused: (processed, queued) =>
        `Scan paused after ${formatIntegerForLocale(processed, 'en')} of ${englishCount(queued, 'discovered entry')}.`,
      interrupted:
        'The scan was interrupted safely. Resume it after checking the authorized folder.',
      stopped:
        'The metadata scan stopped safely. Existing manifest data was not partially replaced.',
      creating: 'Creating a durable local scan job…',
      startDenied: 'A new scan could not start. Resume the existing job if this folder has one.',
      waiting: 'Waiting for the current metadata entry to finish…',
      pauseDenied: 'The pause request could not be recorded safely.',
      revalidating: 'Revalidating the authorized folder boundary…',
      resumeDenied: 'Resume was denied because the job or authorized folder is no longer valid.',
    },
    status: {
      pausing: 'Pausing safely…',
      scanning: 'Scanning metadata…',
      paused: 'Paused',
      interrupted: 'Interrupted safely',
      completed: 'Completed',
      stopped: 'Stopped with an error',
    },
  },
  footer: {
    version: (version) => `DeskGraph ${version}`,
    description: 'Metadata + bounded local text · No uploads · No file operations',
  },
} satisfies Catalog;
