import { formatIntegerForLocale, type Catalog } from './catalog';

const locale = 'zh-CN';

function count(value: number): string {
  return formatIntegerForLocale(value, locale);
}

export const zhCN = {
  metadata: {
    title: 'DeskGraph — 预发布版',
    description: 'DeskGraph 预发布版：本机优先的电脑上下文图谱',
  },
  language: {
    selectorLabel: '显示语言',
  },
  navigation: {
    ariaLabel: '主导航',
    skipToContent: '跳至主要内容',
    brandDescription: '本机优先的电脑上下文',
    localOnly: '仅限本机',
    noNetwork: '不需要网络',
    views: {
      home: {
        label: '首页',
        title: '一眼掌握本机上下文',
        description: '查看这台电脑上的授权、元数据扫描和本机清单状态。',
      },
      search: {
        label: '搜索',
        title: '搜索本机上下文',
        description: '查找当前文件名和明确选择后提取的文本，不会将查询发送到外部。',
      },
      projects: {
        label: '项目',
        title: '已授权文件夹与元数据扫描',
        description: '授权文件夹并运行元数据扫描；此视图尚未提供完整的项目发现功能。',
      },
      inbox: {
        label: '收件箱',
        title: '查看本机建议',
        description: '查看当前本机清理建议；此收件箱无法更改、移至废纸篓、删除或撤销文件。',
      },
      history: {
        label: '历史',
        title: '预览历史',
        description: '查看不含路径的重命名预览；此视图不会执行或撤销文件操作。',
      },
      settings: {
        label: '设置',
        title: '本机运行环境与隐私',
        description: '选择显示语言，并查看仅限本机的运行环境和隐私边界。',
      },
    },
  },
  hero: {
    eyebrow: 'DeskGraph · M2 本机上下文',
    heading: '让你的电脑上下文化。',
    description:
      '一次明确确认一个或多个本机文件夹，建立元数据清单，并将受限文本提取留在这台电脑上，不上传路径或内容。',
    release: '预发布版',
  },
  journey: {
    kicker: '安全的首次操作',
    heading: '三个明确步骤，先看到有用的本机上下文。',
    description:
      '先选择覆盖范围，再扫描元数据，最后只查看你要求的本机建议。DeskGraph 不会一开始就读取整台电脑。',
    privacy: '不上传 · 不自动扫描 · 不更改文件',
    scope: {
      title: '1 · 选择覆盖范围',
      description: '在原生选择器中选择一个或多个文件夹。仅授权不会读取或扫描其中内容。',
      action: '选择本机文件夹',
    },
    search: {
      title: '2 · 扫描后再搜索',
      description:
        '先对选择的文件夹进行初始元数据扫描，再在 SQLite 中搜索文件名与明确选择后提取的文本。',
      action: '打开搜索',
      scanAction: '打开扫描控制',
    },
    review: {
      title: '3 · 查看可解释的建议',
      description: '查看本机项目候选与清理预览；两个页面都不能更改、移至废纸篓、删除或撤销文件。',
      projectsAction: '查看项目',
      cleanupAction: '查看清理建议',
    },
    mcp: {
      title: '只读 MCP 需单独启动',
      description:
        '完成扫描后，独立启动的 macOS/Linux 本机 MCP 切片只能搜索启动时授权的范围。此 Desktop 页面不会配置它，也不提供写入工具。',
    },
    status: {
      noScope: '请先选择覆盖范围',
      scopesReady: (count) => `已授权 ${count} 个文件夹 · 扫描仍需明确启动`,
      scanNeeded: '请先完成初始扫描，才能让搜索、项目或清理评估此文件夹',
      scanReady: '已有完成的本机扫描，可供搜索与查看',
    },
  },
  loading: {
    heading: '正在打开本机清单',
    description: '不会自动扫描任何已授权文件夹。',
  },
  backendError: {
    heading: '本机清单不可用',
    description: '后端没有返回已验证的状态。原始本机错误和路径已隐藏。',
    retry: '重试',
  },
  runtime: {
    kicker: '本机运行环境',
    heading: '清单已就绪',
    localOnly: '仅限本机',
    platform: '平台',
    sqliteManifest: 'SQLite 清单',
    optionalLocalLlm: '可选本机 LLM',
    networkRequired: '需要网络',
    ready: '就绪',
    no: '否',
    lifecycle: { notInitialized: '尚未初始化', disabled: '已禁用' },
  },
  manifest: {
    kicker: '当前图谱',
    emptyHeading: '尚未建立索引',
    readyHeading: '元数据已建立索引',
    files: '文件',
    folders: '文件夹',
    locations: '位置',
    scanIssues: '扫描问题',
  },
  search: {
    kicker: '确定性的本机搜索',
    heading: '查找文件名和已提取文本',
    description:
      '界面使用简体中文；目前经过验证的文本提取与查询语言仍是繁体中文和英文。所有查询都保留在 SQLite 中，且每条结果都会说明命中的本机字段。',
    mode: '词法匹配 · 离线',
    queryLabel: '搜索本机上下文',
    queryPlaceholder: '项目上下文或 project context',
    scopeAria: '搜索文件夹范围',
    allFolders: '所有已授权文件夹',
    authorizedScope: (scopeId) => `已授权范围 ${count(scopeId)}`,
    search: '搜索',
    searching: '正在搜索…',
    filtersAria: '受限的本机搜索筛选条件',
    sourceLabel: '匹配来源',
    sources: {
      all: '路径 + 已提取文本',
      paths: '仅文件名和路径',
      extractedText: '仅已提取文本',
    },
    fileType: '文件类型',
    fileTypePlaceholder: 'md 或 pdf',
    modifiedSince: '修改时间起点（UTC）',
    modifiedBefore: '修改时间终点（UTC，不含）',
    validation: {
      query: '请至少输入 3 个字符，让本机搜索保持受限。',
      extension: '文件类型必须是 1–16 个字符的扩展名，例如 md、pdf 或 docx。',
      dateRange: '请选择有效的 UTC 日期范围，且“修改时间起点”必须早于“修改时间终点”。',
      request: '搜索已安全停止。请尝试较短的查询，或刷新本机清单。',
    },
    empty: (query) => `当前路径或有效的已提取文本没有匹配“${query}”的结果。`,
    summary: (resultCount, elapsedMs) => `${count(resultCount)} 条结果 · ${count(elapsedMs)} 毫秒`,
    filters: {
      scope: (scopeId) => `范围 ${count(scopeId)}`,
      pathsOnly: '仅路径',
      textOnly: '仅已提取文本',
      since: (date) => `自 ${date} UTC 起`,
      before: (date) => `${date} UTC 前`,
      allSources: '所有已授权本机来源',
    },
    explanation: {
      filenameAndText: '精确文件名 + 已提取文本',
      filename: '精确文件名',
      pathAndText: '路径 + 已提取文本',
      path: '文件名或路径',
      text: '已提取文本',
    },
    content: {
      controlsAria: '受限本机文本提取控件',
      notRead: '尚未读取文件内容',
      description: '只会重新验证并在本机读取这个明确选择、已扫描的文本、PDF 或 Office 文件。',
      read: '在本机提取文本',
      readAgain: '再次提取',
      runQueued: '运行排队中的提取',
      reading: '正在安全提取…',
      completed: '受限文本已在本机建立索引。',
      searchExtracted: '搜索已提取文本',
      indexed: '文本已在本机建立索引。请输入文档中的词句进行搜索。',
      failed: '提取已安全停止；任何部分文本都不会替换先前完整索引。',
      denied: '提取已安全拒绝。请重新扫描已更改文件，或选择支持的文件。',
    },
    ocr: {
      controlsAria: '本机截图 OCR 控件',
      notRead: '尚未读取截图文本',
      description:
        '只会重新验证并在这台电脑上读取这张已扫描截图；目前经过验证的识别语言仍是繁体中文和英文。',
      cancel: '取消 OCR',
      stopping: '正在安全停止…',
      retryQueued: '重试排队中的 OCR',
      resume: '继续截图 OCR',
      readAgain: '再次读取截图',
      read: '在本机读取截图文本',
      untrustedText: '不受信任的本机文本',
      queued: '等待开始',
      running: '正在提取受限文本…',
      reading: '正在本机读取截图文本…',
      completed: '截图文本已在本机建立索引',
      cancelled: '已安全取消',
      interrupted: '已安全中断',
      unavailable: '截图 OCR 不可用或已安全跳过',
      skipped: '文件已安全跳过',
      capacity: '另一项本机 OCR 仍在完成中。此任务会保持排队；请安全地重试。',
      providerUnavailable: '截图 OCR 已安全停止。这台电脑上的本机提供程序可能不可用。',
      indexed: '截图文本已在本机建立索引。请再次搜索以查找其内容。',
      cancelledFeedback: '截图 OCR 已安全取消。未发布任何部分文本。',
      interruptedFeedback: '截图 OCR 已安全中断。请继续以在本机完成。',
      failedFeedback: '截图 OCR 已安全停止。先前完整的本机索引已保留。',
      denied: 'OCR 已安全拒绝。若文件已变更，请重新扫描并确认它是受支持的截图。',
      resumeDenied: '继续操作已安全拒绝。请刷新本机清单后再试一次。',
      cancelDenied: '无法安全记录取消请求。',
    },
  },
  actions: {
    kicker: '安全整理预览',
    heading: '先查看重命名，不更改文件',
    description:
      'DeskGraph 会在写入预览记录前，重新验证所选范围、当前清单快照、文件身份、只读打开句柄、建议名称和目标位置。',
    previewOnly: '仅预览 · 不执行',
    folderLabel: '已授权文件夹',
    chooseFolder: '选择已扫描的文件夹',
    scopeOption: (scopeId, path) => `范围 ${count(scopeId)} · ${path}`,
    sourceLabel: '当前绝对文件路径',
    sourcePlaceholder: '/authorized/folder/draft.md',
    newNameLabel: '仅输入建议文件名',
    newNamePlaceholder: 'final.md',
    validating: '正在安全验证…',
    createPreview: '创建持久化预览',
    validation: {
      chooseFolder: '请先选择已授权文件夹。',
      required: '请输入当前绝对文件路径和一个建议文件名。',
      denied:
        '预览已安全拒绝。请重新扫描已变更文件、确认已授权文件夹，并选择未使用且可移植的文件名。',
    },
    previewAria: '已验证的重命名预览',
    plan: (planId) => `计划 ${count(planId)} · 已验证预览`,
    caseOnly: '仅大小写变更的重命名需要未来的分阶段执行器。',
    direct: '直接重命名策略已记录在此持久化预览中。',
    unchanged: '未更改任何文件',
    before: '变更前',
    after: '变更后',
    policyAria: '已通过策略检查',
    policy: {
      authorizedScope: '位于所选已授权文件夹内',
      manifestFile: '当前已扫描文件',
      canonicalSource: '规范化来源仍在范围内',
      sourceIdentity: '平台身份与清单一致',
      readOnlyHandle: '只读打开句柄一致',
      portableName: '可移植的单部分文件名',
      sameParent: '相同的规范化父文件夹',
      destinationScope: '目标位置仍在范围内',
      destinationAvailable: '目标位置可用',
    },
    noExecute: '此 Desktop 页面仅能创建和显示预览；不提供执行或 Undo 控件。',
    historyHeading: '最近不含路径的整理历史',
    plans: (planCount) => `${count(planCount)} 个计划`,
    historyEmpty: '尚未写入任何整理计划。此 Desktop 页面不能执行或 Undo 计划。',
    historyPlan: (planId) => `重命名计划 ${count(planId)}`,
    historyScopeNode: (scopeId, nodeId) => `范围 ${count(scopeId)} · 节点 ${count(nodeId)}`,
    caseOnlyStaged: '仅大小写，已分阶段',
    directStrategy: '直接',
    historyState: {
      previewed: '已预览',
      pending: '处理中',
      executed: '已执行',
      undone: '已 Undo',
      needsAttention: '需要注意',
    },
  },
  watch: {
    kicker: '原生事件提示与安全协调',
    heading: '原生事件提示＋每五分钟安全协调',
    description:
      '原生文件系统事件仅是提示。每五分钟的周期性安全协调也会以受限批次检查符合条件、已完成初始扫描的文件夹；不保证增量内容更新或完成时限。',
    adapterActive: '原生提示＋每五分钟安全协调 · 运行中',
    adapterStarting: '原生提示＋每五分钟安全协调 · 正在启动',
    adapterDegraded: '原生提示或仅周期性备用 · 需要注意',
    adapterStopped: '原生提示＋每五分钟安全协调 · 已停止',
    metrics: {
      recent: '最近事件',
      observed: '观察到的提示',
      reconciled: '已协调',
      deferred: '已延后文件夹',
      attention: '需要注意',
    },
    empty:
      '尚未观察到变化。已到期且完成初始扫描的文件夹会在本机分批安排；新授权文件夹仍须先明确执行初始扫描。',
    status: {
      stabilizing: '等待稳定快照',
      reconciling: '原子化清单协调',
      completed: '已协调',
      noFailure: '没有失败',
    },
    reason: {
      temporary: '已忽略临时下载',
      hidden: '已忽略隐藏项目',
      unsupported: '已忽略不支持的项目',
      unavailable: '来源不可用',
      failed: '协调已安全失败',
    },
    event: (eventId, scopeId, hints) =>
      `事件 ${count(eventId)} · 范围 ${count(scopeId)} · ${count(hints)} 个合并提示`,
    scan: (jobId) => `扫描 ${count(jobId)}`,
    noScan: '尚未扫描',
  },
  cleanup: {
    kicker: '智能清理收件箱',
    heading: '查看本机清理建议',
    description:
      '明确选择一个已授权文件夹后，才会刷新当前的重复文件、旧版本和截图群组证据；只读取本机证据。',
    suggestionOnly: '仅建议 · 不更改文件',
    scopeLabel: '已授权文件夹',
    chooseScope: '选择已授权文件夹',
    refresh: '刷新建议',
    refreshing: '正在刷新本机证据…',
    controlsAria: '智能清理收件箱控件',
    authorizationRequired: '请先授权一个文件夹，才能请求本机清理建议。',
    empty: '此已授权文件夹没有当前可查看的清理建议。',
    partial: (notCurrent) =>
      notCurrent === 0
        ? '此次受限刷新尚未完整；部分来源无法安全完成评估。'
        : `此次受限刷新尚未完整。已有 ${count(notCurrent)} 条较旧建议因证据不再是当前状态而被排除。`,
    error: '无法安全刷新建议；未更改任何文件。',
    exactDuplicate: '完全重复文件',
    version: '旧版本候选项',
    screenshotReviewGroup: '截图审阅群组',
    exactDuplicateExplanation:
      '这一对文件已完成受限的完整字节比对；这不会选择保留文件，也不授权清理。',
    versionExplanation:
      '明确的数字 vN 文件名规则只指出较小到较大的版本方向；不代表较旧文件可安全丢弃。',
    screenshotReviewGroupExplanation:
      '相同尺寸、十分钟时间窗与当前 OCR 来源证据只用于辅助群组审阅；不证明截图来源、内容相似、重复或可丢弃。',
    itemMeta: (members, evidenceScoreBasisPoints, observedAt) =>
      `${count(members)} 个成员 · 证据分数 ${count(evidenceScoreBasisPoints)} / 10,000 · 观察于 ${observedAt}`,
    verification:
      '打开查看后会先重新验证当前证据，才能创建持久预览。此收件箱无法确认、移动、移至废纸篓、删除、还原或撤销文件。',
    review: {
      open: '查看文件并创建预览',
      loading: '正在本机重新验证此建议…',
      close: '关闭文件查看',
      transientNotice:
        '路径只会显示在这次明确请求的本机查看中，不会写入清理计划、历史记录、日志或语言偏好。',
      selectionLegend: '选择一个清理预览目标',
      selectTarget: '选为预览目标',
      keeper: '保留作为比对文件',
      keeperSwitch: '将保留此文件 · 选中后可改为预览目标',
      noKeeper: '截图查看不指定保留文件；每个预览只绑定一个目标。',
      roles: {
        duplicateCandidate: '完全重复候选文件',
        olderVersion: '较旧版本 · 可选目标',
        newerVersion: '较新版本 · 必须保留',
        screenshotCandidate: '截图群组成员',
      },
      memberSize: (bytes) => `${count(bytes)} 字节`,
      createPreview: '创建持久预览',
      creatingPreview: '正在绑定当前文件证据…',
      selectionRequired: '请先选择一个要预览的文件。',
      detailError: '此建议已无法安全查看；请刷新收件箱后重试。',
      previewError: '文件或证据在预览封存前已发生变化；未授权任何操作。',
      previewReady: (planId) => `预览 ${count(planId)} 已在本机封存`,
      expectedBytesLabel: '绑定文件大小',
      expectedBytes: (bytes) => `此预览已绑定 ${count(bytes)} 字节`,
      journalLabel: '日志',
      journalSequence: (sequence) => `不可变日志序号 ${count(sequence)}`,
      checksLabel: '策略验证',
      checksPassed: (checkCount) => `已记录 ${count(checkCount)} 项策略检查`,
      noExecution: '仅供预览。这不会确认、移动、移至废纸篓、删除、还原或撤销任何文件。',
    },
  },
  projects: {
    kicker: '项目发现',
    heading: '查看本机项目建议',
    description: '明确评估一个已扫描授权文件夹中的确定性本机文件夹标记。',
    scopeLabel: '已授权文件夹',
    chooseScope: '选择已授权文件夹',
    discover: '发现项目',
    discovering: '正在评估本机文件夹证据…',
    checkingReadiness: '正在确认持久化扫描状态…',
    readinessError: '无法安全确认此文件夹的扫描状态。',
    controlsAria: '项目发现控件',
    authorizationRequired: '请先授权一个文件夹，才能请求本机项目建议。',
    scanRequired: '请先完成此文件夹的元数据扫描，再发现项目。',
    empty: '没有找到当前的文件夹标记项目建议。',
    partial: '此次受限评估尚未完整；部分根目录无法安全评估。',
    error: '无法安全评估项目建议。',
    candidateMeta: (confidence, observedAt) =>
      `证据分数 ${count(confidence)} / 10,000 · 观察于 ${observedAt}`,
    viewEvidence: '查看证据',
    suggestionOnly: '仅建议',
    noAutomaticMembership: '接受根目录不会创建文件归属关系。',
    noFileActions: '不会移动、重命名、删除、移至废纸篓或还原文件。',
    state: {
      suggested: '建议的项目根目录',
      accepted: '已接受项目根目录',
      rejected: '已拒绝项目根目录',
    },
    detail: {
      loading: '正在重新验证此项目建议…',
      transientNotice: '只有这次明确请求的本机查看会显示当前路径；普通列表或日志不会包含它。',
      rootLabel: '当前项目根目录',
      signalsLabel: '观察到的文件夹标记',
      close: '关闭项目查看',
      accept: '接受项目根目录',
      reject: '拒绝项目根目录',
      saving: '正在保存你的追加式决定…',
      decisionError: '无法安全保存决定。',
      detailError: '此项目建议已不再是当前状态；请刷新后重试。',
    },
  },
  extraction: {
    kicker: '受限的本机内容',
    emptyHeading: '尚未提取任何文件内容',
    readyHeading: '本机文本已就绪',
    description:
      '只有已扫描且受支持的文档与明确选取的截图符合条件。每个来源都会重新验证，输出受大小限制，失败任务不能取代上次完整文本。',
    neverUploaded: '绝不上传',
    metrics: {
      files: '含文本的文件',
      chunks: '活动分块',
      completed: '已完成任务',
      skipped: '已跳过或取消',
    },
    latest: (operation, jobId) => `最新 ${operation} 任务 ${count(jobId)}`,
    operation: { screenshotOcr: '截图 OCR', content: '内容' },
    progress: (chunks, bytes) => `${count(chunks)} 个分块 · ${count(bytes)} 字节`,
    optInEmpty: '内容提取需要明确选择。授权或扫描文件夹绝不会读取文件内容。',
  },
  scope: {
    kicker: '明确授权',
    heading: 'DeskGraph 可以检查的文件夹',
    description:
      '请在同一个系统选择器中选择一个或多个文件夹。DeskGraph 只会访问你确认的范围；授权和扫描是分开的操作，选择本身不会开始扫描，也不会跟踪符号链接或隐藏项目。',
    count: (scopeCount) => `${count(scopeCount)} 个已授权`,
    pickerAriaLabel: '使用系统选择器选择一个或多个文件夹',
    authorize: '选择要授权的文件夹',
    emptyHeading: '没有文件夹访问权限',
    emptyDescription: '在这里添加前，DeskGraph 无法检查桌面、下载项或文档。',
    label: (scopeId) => `已授权范围 ${count(scopeId)}`,
    progress: (processed, queued, issues) =>
      `${count(processed)} / ${count(queued)} 个项目 · ${count(issues)} 个问题`,
    pause: '暂停扫描',
    pausing: '正在安全暂停…',
    resume: '继续扫描',
    scan: '扫描元数据',
    validation: {
      cancelled: '已取消文件夹选择，没有提交任何授权变更。',
      validating: '等待你选择文件夹，然后逐一验证所有文件夹边界…',
      authorized: (scopeCount) =>
        `已一次授权 ${count(scopeCount)} 个文件夹，尚未扫描；准备好后请为各范围选择“扫描元数据”。`,
      refreshFailed: (scopeCount) =>
        `已授权 ${count(scopeCount)} 个文件夹且尚未扫描，但无法刷新最新本机状态；请重新加载以同步界面。`,
      denied:
        '无法将所选文件夹作为一组授权，没有提交任何所选变更。请移除不可用、受保护、重复或重叠的文件夹后重试。',
      reading: '正在读取已授权文件夹中的元数据…',
      complete: (files, folders) =>
        `扫描完成：${count(files)} 个文件和 ${count(folders)} 个文件夹。`,
      paused: (processed, queued) =>
        `扫描已在发现 ${count(queued)} 个项目中的 ${count(processed)} 个后暂停。`,
      interrupted: '扫描已安全中断。检查已授权文件夹后请继续。',
      stopped: '元数据扫描已安全停止。现有清单数据未被部分替换。',
      creating: '正在创建持久化的本机扫描任务…',
      startDenied: '无法启动新的扫描。若此文件夹已有任务，请继续该任务。',
      waiting: '正在等待当前元数据项目完成…',
      pauseDenied: '无法安全记录暂停请求。',
      revalidating: '正在重新验证已授权文件夹边界…',
      resumeDenied: '继续操作被拒绝，因为任务或已授权文件夹不再有效。',
    },
    status: {
      pausing: '正在安全暂停…',
      scanning: '正在扫描元数据…',
      paused: '已暂停',
      interrupted: '已安全中断',
      completed: '已完成',
      stopped: '因错误停止',
    },
  },
  hardExclusion: {
    kicker: '覆盖范围隐私',
    heading: '硬性排除',
    description: '硬性排除会拒绝本机访问和索引；不是只隐藏搜索结果。',
    scopeLabel: '已授权根目录',
    chooseScope: '选择已授权根目录',
    loading: '正在加载当前策略…',
    policyRevision: (revision) => `策略修订版 ${revision}`,
    addFolders: '添加文件夹…',
    addFiles: '添加文件…',
    noExclusions: '此根目录没有硬性排除项。',
    currentExclusions: '当前硬性排除项',
    removalUnavailable: '此版本切片尚未提供移除硬性排除的功能。',
    previewHeading: '查看硬性排除',
    previewNotice: 'DeskGraph 会清除受影响的本机索引数据；不会移动或删除源文件。',
    previewEmpty: '已取消原生选择器，未更改策略。',
    notConfirmable: '当前文件操作或可恢复 journal 工作尚未完成，因此无法确认此排除。源文件未更改。',
    item: {
      willAdd: '将排除',
      alreadyExcluded: '已排除',
      coveredByParent: '已由所选文件夹涵盖',
      file: '文件',
      folder: '文件夹',
    },
    impact: (locations, content, graph, candidates, jobs, actions) =>
      `本机会影响 ${locations} 个位置、${content} 个内容／OCR 块、${graph} 个图谱事实、${candidates} 个派生候选、${jobs} 个待处理任务，以及 ${actions} 条会阻止此次更改的操作安全记录。`,
    confirm: '确认排除并清除本机索引',
    confirming: '正在确认隐私清除…',
    cancel: '取消预览',
    cancelled: '预览已取消，未更改策略。',
    committed: (count) => `已保存 ${count} 个硬性排除项，并清除受影响的本机索引数据。`,
    refreshFailed: (count) => `已保存 ${count} 个硬性排除项并清除本机数据，但刷新失败。`,
    error: '未确认硬性排除；不会报告本机隐私清除已完成。',
    sourceSafe: '不会移动、更改或删除源文件。',
  },
  footer: {
    version: (version) => `DeskGraph ${version}`,
    description: '元数据 + 受限本机文本 · 不上传 · 不进行文件操作',
  },
} satisfies Catalog;
