import { formatIntegerForLocale, type Catalog } from './catalog';

const locale = 'zh-CN';

function count(value: number): string {
  return formatIntegerForLocale(value, locale);
}

export const zhCN = {
  metadata: {
    title: 'DeskGraph — 预发布版',
    description: 'DeskGraph 预发布版：本机优先的电脑上下文图谱',
  },
  language: {
    selectorLabel: '显示语言',
  },
  hero: {
    eyebrow: 'DeskGraph · M2 本机上下文',
    heading: '让你的电脑上下文化。',
    description:
      '一次只明确授权一个本机文件夹，建立元数据清单，并将受限文本提取留在这台电脑上，不上传路径或内容。',
    release: '预发布版',
  },
  loading: {
    heading: '正在打开本机清单',
    description: '不会自动扫描任何已授权文件夹。',
  },
  backendError: {
    heading: '本机清单不可用',
    description: '后端没有返回已验证的状态。原始本机错误和路径已隐藏。',
    retry: '重试',
  },
  runtime: {
    kicker: '本机运行环境',
    heading: '清单已就绪',
    localOnly: '仅限本机',
    platform: '平台',
    sqliteManifest: 'SQLite 清单',
    optionalLocalLlm: '可选本机 LLM',
    networkRequired: '需要网络',
    ready: '就绪',
    no: '否',
    lifecycle: { notInitialized: '尚未初始化', disabled: '已禁用' },
  },
  manifest: {
    kicker: '当前图谱',
    emptyHeading: '尚未建立索引',
    readyHeading: '元数据已建立索引',
    files: '文件',
    folders: '文件夹',
    locations: '位置',
    scanIssues: '扫描问题',
  },
  search: {
    kicker: '确定性的本机搜索',
    heading: '查找文件名和已提取文本',
    description:
      '界面使用简体中文；目前经过验证的文本提取与查询语言仍是繁体中文和英文。所有查询都保留在 SQLite 中，且每条结果都会说明命中的本机字段。',
    mode: '词法匹配 · 离线',
    queryLabel: '搜索本机上下文',
    queryPlaceholder: '项目上下文或 project context',
    scopeAria: '搜索文件夹范围',
    allFolders: '所有已授权文件夹',
    authorizedScope: (scopeId) => `已授权范围 ${count(scopeId)}`,
    search: '搜索',
    searching: '正在搜索…',
    filtersAria: '受限的本机搜索筛选条件',
    sourceLabel: '匹配来源',
    sources: {
      all: '路径 + 已提取文本',
      paths: '仅文件名和路径',
      extractedText: '仅已提取文本',
    },
    fileType: '文件类型',
    fileTypePlaceholder: 'md 或 pdf',
    modifiedSince: '修改时间起点（UTC）',
    modifiedBefore: '修改时间终点（UTC，不含）',
    validation: {
      query: '请至少输入 3 个字符，让本机搜索保持受限。',
      extension: '文件类型必须是 1–16 个字符的扩展名，例如 md、pdf 或 docx。',
      dateRange: '请选择有效的 UTC 日期范围，且“修改时间起点”必须早于“修改时间终点”。',
      request: '搜索已安全停止。请尝试较短的查询，或刷新本机清单。',
    },
    empty: (query) => `当前路径或有效的已提取文本没有匹配“${query}”的结果。`,
    summary: (resultCount, elapsedMs) => `${count(resultCount)} 条结果 · ${count(elapsedMs)} 毫秒`,
    filters: {
      scope: (scopeId) => `范围 ${count(scopeId)}`,
      pathsOnly: '仅路径',
      textOnly: '仅已提取文本',
      since: (date) => `自 ${date} UTC 起`,
      before: (date) => `${date} UTC 前`,
      allSources: '所有已授权本机来源',
    },
    explanation: {
      filenameAndText: '精确文件名 + 已提取文本',
      filename: '精确文件名',
      pathAndText: '路径 + 已提取文本',
      path: '文件名或路径',
      text: '已提取文本',
    },
    ocr: {
      controlsAria: '本机截图 OCR 控件',
      notRead: '尚未读取截图文本',
      description:
        '只会重新验证并在这台电脑上读取这张已扫描截图；目前经过验证的识别语言仍是繁体中文和英文。',
      cancel: '取消 OCR',
      stopping: '正在安全停止…',
      retryQueued: '重试排队中的 OCR',
      resume: '继续截图 OCR',
      readAgain: '再次读取截图',
      read: '在本机读取截图文本',
      untrustedText: '不受信任的本机文本',
      queued: '等待开始',
      running: '正在提取受限文本…',
      reading: '正在本机读取截图文本…',
      completed: '截图文本已在本机建立索引',
      cancelled: '已安全取消',
      interrupted: '已安全中断',
      unavailable: '截图 OCR 不可用或已安全跳过',
      skipped: '文件已安全跳过',
      capacity: '另一项本机 OCR 仍在完成中。此任务会保持排队；请安全地重试。',
      providerUnavailable: '截图 OCR 已安全停止。这台电脑上的本机提供程序可能不可用。',
      indexed: '截图文本已在本机建立索引。请再次搜索以查找其内容。',
      cancelledFeedback: '截图 OCR 已安全取消。未发布任何部分文本。',
      interruptedFeedback: '截图 OCR 已安全中断。请继续以在本机完成。',
      failedFeedback: '截图 OCR 已安全停止。先前完整的本机索引已保留。',
      denied: 'OCR 已安全拒绝。若文件已变更，请重新扫描并确认它是受支持的截图。',
      resumeDenied: '继续操作已安全拒绝。请刷新本机清单后再试一次。',
      cancelDenied: '无法安全记录取消请求。',
    },
  },
  actions: {
    kicker: '安全整理预览',
    heading: '先查看重命名，不更改文件',
    description:
      'DeskGraph 会在写入预览记录前，重新验证所选范围、当前清单快照、文件身份、只读打开句柄、建议名称和目标位置。',
    previewOnly: '仅预览 · 不执行',
    folderLabel: '已授权文件夹',
    chooseFolder: '选择已扫描的文件夹',
    scopeOption: (scopeId, path) => `范围 ${count(scopeId)} · ${path}`,
    sourceLabel: '当前绝对文件路径',
    sourcePlaceholder: '/authorized/folder/draft.md',
    newNameLabel: '仅输入建议文件名',
    newNamePlaceholder: 'final.md',
    validating: '正在安全验证…',
    createPreview: '创建持久化预览',
    validation: {
      chooseFolder: '请先选择已授权文件夹。',
      required: '请输入当前绝对文件路径和一个建议文件名。',
      denied:
        '预览已安全拒绝。请重新扫描已变更文件、确认已授权文件夹，并选择未使用且可移植的文件名。',
    },
    previewAria: '已验证的重命名预览',
    plan: (planId) => `计划 ${count(planId)} · 已验证预览`,
    caseOnly: '仅大小写变更的重命名需要未来的分阶段执行器。',
    direct: '已记录直接重命名策略，供未来执行器使用。',
    unchanged: '未更改任何文件',
    before: '变更前',
    after: '变更后',
    policyAria: '已通过策略检查',
    policy: {
      authorizedScope: '位于所选已授权文件夹内',
      manifestFile: '当前已扫描文件',
      canonicalSource: '规范化来源仍在范围内',
      sourceIdentity: '平台身份与清单一致',
      readOnlyHandle: '只读打开句柄一致',
      portableName: '可移植的单部分文件名',
      sameParent: '相同的规范化父文件夹',
      destinationScope: '目标位置仍在范围内',
      destinationAvailable: '目标位置可用',
    },
    noExecute: '此计划已写入日志，但不能执行。恢复和撤销尚未存在，因此 DeskGraph 不提供操作按钮。',
    historyHeading: '最近不含路径的预览历史',
    plans: (planCount) => `${count(planCount)} 个计划`,
    historyEmpty: '尚未写入任何整理预览。此应用无法更改文件。',
    historyPlan: (planId) => `重命名预览 ${count(planId)}`,
    historyScopeNode: (scopeId, nodeId) => `范围 ${count(scopeId)} · 节点 ${count(nodeId)}`,
    caseOnlyStaged: '仅大小写，已分阶段',
    directPreviewed: '直接 · 已预览',
  },
  watch: {
    kicker: '原生事件提示与安全协调',
    heading: '原生事件提示＋每五分钟安全协调',
    description:
      '原生文件系统事件仅是提示。每五分钟的周期性安全协调也会以受限批次检查符合条件、已完成初始扫描的文件夹；不保证增量内容更新或完成时限。',
    adapterActive: '原生提示＋每五分钟安全协调 · 运行中',
    adapterStarting: '原生提示＋每五分钟安全协调 · 正在启动',
    adapterDegraded: '原生提示或仅周期性备用 · 需要注意',
    adapterStopped: '原生提示＋每五分钟安全协调 · 已停止',
    metrics: {
      recent: '最近事件',
      observed: '观察到的提示',
      reconciled: '已协调',
      deferred: '已延后文件夹',
      attention: '需要注意',
    },
    empty:
      '尚未观察到变化。已到期且完成初始扫描的文件夹会在本机分批安排；新授权文件夹仍须先明确执行初始扫描。',
    status: {
      stabilizing: '等待稳定快照',
      reconciling: '原子化清单协调',
      completed: '已协调',
      noFailure: '没有失败',
    },
    reason: {
      temporary: '已忽略临时下载',
      hidden: '已忽略隐藏项目',
      unsupported: '已忽略不支持的项目',
      unavailable: '来源不可用',
      failed: '协调已安全失败',
    },
    event: (eventId, scopeId, hints) =>
      `事件 ${count(eventId)} · 范围 ${count(scopeId)} · ${count(hints)} 个合并提示`,
    scan: (jobId) => `扫描 ${count(jobId)}`,
    noScan: '尚未扫描',
  },
  extraction: {
    kicker: '受限的本机内容',
    emptyHeading: '尚未提取任何文件内容',
    readyHeading: '本机文本已就绪',
    description:
      '只有已扫描且受支持的文档与明确选取的截图符合条件。每个来源都会重新验证，输出受大小限制，失败任务不能取代上次完整文本。',
    neverUploaded: '绝不上传',
    metrics: {
      files: '含文本的文件',
      chunks: '活动分块',
      completed: '已完成任务',
      skipped: '已跳过或取消',
    },
    latest: (operation, jobId) => `最新 ${operation} 任务 ${count(jobId)}`,
    operation: { screenshotOcr: '截图 OCR', content: '内容' },
    progress: (chunks, bytes) => `${count(chunks)} 个分块 · ${count(bytes)} 字节`,
    optInEmpty: '内容提取需要明确选择。授权或扫描文件夹绝不会读取文件内容。',
  },
  scope: {
    kicker: '明确授权',
    heading: 'DeskGraph 可以检查的文件夹',
    description: '请输入现有文件夹路径。授权和扫描是分开的操作；不会跟踪符号链接或隐藏项目。',
    count: (scopeCount) => `${count(scopeCount)} 个已授权`,
    inputLabel: '文件夹路径',
    placeholder: '/Users/you/Documents 或 C:\\Users\\you\\Documents',
    authorize: '授权文件夹',
    emptyHeading: '没有文件夹访问权限',
    emptyDescription: '在这里添加前，DeskGraph 无法检查桌面、下载项或文档。',
    label: (scopeId) => `已授权范围 ${count(scopeId)}`,
    progress: (processed, queued, issues) =>
      `${count(processed)} / ${count(queued)} 个项目 · ${count(issues)} 个问题`,
    pause: '暂停扫描',
    pausing: '正在安全暂停…',
    resume: '继续扫描',
    scan: '扫描元数据',
    validation: {
      required: '请先输入现有文件夹路径。',
      validating: '正在验证文件夹边界…',
      authorized: '文件夹已授权。在你选择“扫描元数据”前不会扫描任何内容。',
      denied: '无法授权此文件夹。请确认它存在且未受保护。',
      reading: '正在读取已授权文件夹中的元数据…',
      complete: (files, folders) =>
        `扫描完成：${count(files)} 个文件和 ${count(folders)} 个文件夹。`,
      paused: (processed, queued) =>
        `扫描已在发现 ${count(queued)} 个项目中的 ${count(processed)} 个后暂停。`,
      interrupted: '扫描已安全中断。检查已授权文件夹后请继续。',
      stopped: '元数据扫描已安全停止。现有清单数据未被部分替换。',
      creating: '正在创建持久化的本机扫描任务…',
      startDenied: '无法启动新的扫描。若此文件夹已有任务，请继续该任务。',
      waiting: '正在等待当前元数据项目完成…',
      pauseDenied: '无法安全记录暂停请求。',
      revalidating: '正在重新验证已授权文件夹边界…',
      resumeDenied: '继续操作被拒绝，因为任务或已授权文件夹不再有效。',
    },
    status: {
      pausing: '正在安全暂停…',
      scanning: '正在扫描元数据…',
      paused: '已暂停',
      interrupted: '已安全中断',
      completed: '已完成',
      stopped: '因错误停止',
    },
  },
  footer: {
    version: (version) => `DeskGraph ${version}`,
    description: '元数据 + 受限本机文本 · 不上传 · 不进行文件操作',
  },
} satisfies Catalog;
