import { formatIntegerForLocale, type Catalog } from './catalog';

export const zhTW = {
  metadata: {
    title: 'DeskGraph — 預先發行版',
    description: 'DeskGraph 預先發行版：本機優先的電腦脈絡圖譜',
  },
  language: {
    selectorLabel: '顯示語言',
  },
  hero: {
    eyebrow: 'DeskGraph · M2 本機脈絡',
    heading: '讓你的電腦脈絡化。',
    description:
      '一次明確授權一個本機資料夾，建立其中繼資料清單，並將受限文字抽取留在這台電腦上，不上傳路徑或內容。',
    release: '預先發行版',
  },
  loading: { heading: '正在開啟本機清單', description: '不會自動掃描任何已授權資料夾。' },
  backendError: {
    heading: '本機清單無法使用',
    description: '後端未回傳已驗證的狀態。原始本機錯誤與路徑已隱藏。',
    retry: '重試',
  },
  runtime: {
    kicker: '本機執行環境',
    heading: '清單已就緒',
    localOnly: '僅限本機',
    platform: '平台',
    sqliteManifest: 'SQLite 清單',
    optionalLocalLlm: '選用的本機 LLM',
    networkRequired: '需要網路',
    ready: '就緒',
    no: '否',
    lifecycle: { notInitialized: '尚未初始化', disabled: '已停用' },
  },
  manifest: {
    kicker: '目前圖譜',
    emptyHeading: '尚未建立索引',
    readyHeading: '中繼資料已建立索引',
    files: '檔案',
    folders: '資料夾',
    locations: '位置',
    scanIssues: '掃描問題',
  },
  search: {
    kicker: '可預測的本機搜尋',
    heading: '尋找檔名與已抽取文字',
    description:
      '繁體中文與英文查詢都留在 SQLite 內。嵌入功能已關閉；每筆結果都會說明命中的本機欄位。',
    mode: '字面比對 · 離線',
    queryLabel: '搜尋本機脈絡',
    queryPlaceholder: '專案脈絡或 project context',
    scopeAria: '搜尋資料夾範圍',
    allFolders: '所有已授權資料夾',
    authorizedScope: (scopeId) => `已授權範圍 ${scopeId}`,
    search: '搜尋',
    searching: '正在搜尋…',
    filtersAria: '受限的本機搜尋篩選條件',
    sourceLabel: '比對來源',
    sources: { all: '路徑 + 已抽取文字', paths: '僅檔名與路徑', extractedText: '僅已抽取文字' },
    fileType: '檔案類型',
    fileTypePlaceholder: 'md 或 pdf',
    modifiedSince: '修改時間起點（UTC）',
    modifiedBefore: '修改時間終點（UTC，不含）',
    validation: {
      query: '請至少輸入 3 個字元，讓本機搜尋維持受限。',
      extension: '檔案類型必須是 1–16 個字元的副檔名，例如 md、pdf 或 docx。',
      dateRange: '請選擇有效的 UTC 日期範圍，且「修改時間起點」必須早於「修改時間終點」。',
      request: '搜尋已安全停止。請嘗試較短的查詢，或重新整理本機清單。',
    },
    empty: (query) => `目前路徑或有效的已抽取文字沒有符合「${query}」的結果。`,
    summary: (count, elapsedMs) =>
      `${formatIntegerForLocale(count, 'zh-TW')} 筆結果 · ${formatIntegerForLocale(elapsedMs, 'zh-TW')} 毫秒`,
    filters: {
      scope: (scopeId) => `範圍 ${scopeId}`,
      pathsOnly: '僅路徑',
      textOnly: '僅已抽取文字',
      since: (date) => `自 ${date} UTC 起`,
      before: (date) => `${date} UTC 前`,
      allSources: '所有已授權本機來源',
    },
    explanation: {
      filenameAndText: '精確檔名 + 已抽取文字',
      filename: '精確檔名',
      pathAndText: '路徑 + 已抽取文字',
      path: '檔名或路徑',
      text: '已抽取文字',
    },
    ocr: {
      controlsAria: '本機截圖 OCR 控制項',
      notRead: '尚未讀取截圖文字',
      description: '只會重新驗證並在這台電腦上讀取這張已掃描截圖。',
      cancel: '取消 OCR',
      stopping: '正在安全停止…',
      retryQueued: '重試排隊中的 OCR',
      resume: '繼續截圖 OCR',
      readAgain: '再次讀取截圖',
      read: '在本機讀取截圖文字',
      untrustedText: '未受信任的本機文字',
      queued: '等待開始',
      running: '正在抽取受限文字…',
      reading: '正在本機讀取截圖文字…',
      completed: '截圖文字已在本機建立索引',
      cancelled: '已安全取消',
      interrupted: '已安全中斷',
      unavailable: '截圖 OCR 無法使用或已安全略過',
      skipped: '檔案已安全略過',
      capacity: '另一項本機 OCR 仍在完成中。此工作會維持排隊；請安全地重試。',
      providerUnavailable: '截圖 OCR 已安全停止。此電腦上的本機提供者可能無法使用。',
      indexed: '截圖文字已在本機建立索引。請再次搜尋以找到內容。',
      cancelledFeedback: '截圖 OCR 已安全取消。未發布任何部分文字。',
      interruptedFeedback: '截圖 OCR 已安全中斷。請繼續以在本機完成。',
      failedFeedback: '截圖 OCR 已安全停止。先前完整的本機索引已保留。',
      denied: 'OCR 已安全拒絕。若檔案已變更，請重新掃描並確認它是支援的截圖。',
      resumeDenied: '繼續操作已安全拒絕。請重新整理本機清單後再試一次。',
      cancelDenied: '無法安全記錄取消要求。',
    },
  },
  actions: {
    kicker: '安全整理預覽',
    heading: '先檢視重新命名，不變更檔案',
    description:
      'DeskGraph 會在寫入預覽紀錄前，重新驗證所選範圍、目前清單快照、檔案身分、唯讀開啟控制代碼、建議名稱與目的地。',
    previewOnly: '僅預覽 · 不執行',
    folderLabel: '已授權資料夾',
    chooseFolder: '選擇已掃描的資料夾',
    scopeOption: (scopeId, path) => `範圍 ${scopeId} · ${path}`,
    sourceLabel: '目前絕對檔案路徑',
    sourcePlaceholder: '/authorized/folder/draft.md',
    newNameLabel: '僅輸入建議檔名',
    newNamePlaceholder: 'final.md',
    validating: '正在安全驗證…',
    createPreview: '建立可持久化預覽',
    validation: {
      chooseFolder: '請先選擇已授權資料夾。',
      required: '請輸入目前絕對檔案路徑與一個建議檔名。',
      denied: '預覽已安全拒絕。請重新掃描已變更檔案、確認已授權資料夾，並選擇未使用且可攜的檔名。',
    },
    previewAria: '已驗證的重新命名預覽',
    plan: (planId) => `計畫 ${planId} · 已驗證預覽`,
    caseOnly: '僅大小寫的重新命名需要未來分階段執行器。',
    direct: '直接重新命名策略已記錄在此可持久化預覽中。',
    unchanged: '未變更任何檔案',
    before: '變更前',
    after: '變更後',
    policyAria: '已通過的政策檢查',
    policy: {
      authorizedScope: '位於選取的已授權資料夾內',
      manifestFile: '目前已掃描檔案',
      canonicalSource: '正規化來源仍在範圍內',
      sourceIdentity: '平台身分符合清單',
      readOnlyHandle: '唯讀開啟控制代碼相符',
      portableName: '可攜式單一部分檔名',
      sameParent: '相同的正規化父資料夾',
      destinationScope: '目的地仍在範圍內',
      destinationAvailable: '目的地可用',
    },
    noExecute: '此 Desktop 畫面僅能建立與顯示預覽；不提供執行或 Undo 控制項。',
    historyHeading: '最近不含路徑的整理紀錄',
    plans: (count) => `${formatIntegerForLocale(count, 'zh-TW')} 個計畫`,
    historyEmpty: '尚未寫入任何整理計畫。此 Desktop 畫面不能執行或 Undo 計畫。',
    historyPlan: (planId) => `重新命名計畫 ${planId}`,
    historyScopeNode: (scopeId, nodeId) => `範圍 ${scopeId} · 節點 ${nodeId}`,
    caseOnlyStaged: '僅大小寫，已分階段',
    directStrategy: '直接',
    historyState: {
      previewed: '已預覽',
      pending: '處理中',
      executed: '已執行',
      undone: '已 Undo',
      needsAttention: '需要注意',
    },
  },
  watch: {
    kicker: '原生事件提示與安全協調',
    heading: '原生事件提示＋每五分鐘安全協調',
    description:
      '原生檔案系統事件僅是提示。每五分鐘的週期性安全協調也會以受限批次檢查符合資格、已完成初始掃描的資料夾；不保證增量內容更新或完成時限。',
    adapterActive: '原生提示＋每五分鐘安全協調 · 運作中',
    adapterStarting: '原生提示＋每五分鐘安全協調 · 啟動中',
    adapterDegraded: '原生提示或僅週期性備援 · 需要注意',
    adapterStopped: '原生提示＋每五分鐘安全協調 · 已停止',
    metrics: {
      recent: '最近事件',
      observed: '觀察到的提示',
      reconciled: '已協調',
      deferred: '延後資料夾',
      attention: '需要注意',
    },
    empty:
      '尚未觀察到變更。已到期且完成初始掃描的資料夾會在本機分批排程；新授權資料夾仍須先明確執行初始掃描。',
    status: {
      stabilizing: '等待穩定快照',
      reconciling: '原子化清單協調',
      completed: '已協調',
      noFailure: '沒有失敗',
    },
    reason: {
      temporary: '已忽略暫存下載',
      hidden: '已忽略隱藏項目',
      unsupported: '已忽略不支援項目',
      unavailable: '來源無法使用',
      failed: '協調已安全失敗',
    },
    event: (eventId, scopeId, hints) =>
      `事件 ${eventId} · 範圍 ${scopeId} · ${formatIntegerForLocale(hints, 'zh-TW')} 個合併提示`,
    scan: (jobId) => `掃描 ${jobId}`,
    noScan: '尚未掃描',
  },
  extraction: {
    kicker: '受限的本機內容',
    emptyHeading: '尚未抽取任何檔案內容',
    readyHeading: '本機文字已就緒',
    description:
      '只有已掃描且支援的文件與明確選取的截圖符合資格。每個來源都會重新驗證，輸出受大小限制，失敗工作無法取代上次完整文字。',
    neverUploaded: '絕不上傳',
    metrics: {
      files: '含文字的檔案',
      chunks: '有效區塊',
      completed: '已完成工作',
      skipped: '已略過或取消',
    },
    latest: (operation, jobId) => `最新 ${operation} 工作 ${jobId}`,
    operation: { screenshotOcr: '截圖 OCR', content: '內容' },
    progress: (chunks, bytes) =>
      `${formatIntegerForLocale(chunks, 'zh-TW')} 個區塊 · ${formatIntegerForLocale(bytes, 'zh-TW')} 位元組`,
    optInEmpty: '內容抽取需明確選擇。授權或掃描資料夾絕不會讀取檔案內容。',
  },
  scope: {
    kicker: '明確授權',
    heading: 'DeskGraph 可檢查的資料夾',
    description: '請輸入既有資料夾路徑。授權與掃描是分開的操作；不會追蹤符號連結或隱藏項目。',
    count: (count) => `${formatIntegerForLocale(count, 'zh-TW')} 個已授權`,
    inputLabel: '資料夾路徑',
    placeholder: '/Users/you/Documents 或 C:\\Users\\you\\Documents',
    authorize: '授權資料夾',
    emptyHeading: '沒有資料夾存取權',
    emptyDescription: '在這裡新增前，DeskGraph 無法檢查桌面、下載項目或文件。',
    label: (scopeId) => `已授權範圍 ${scopeId}`,
    progress: (processed, queued, issues) =>
      `${formatIntegerForLocale(processed, 'zh-TW')} / ${formatIntegerForLocale(queued, 'zh-TW')} 個項目 · ${formatIntegerForLocale(issues, 'zh-TW')} 個問題`,
    pause: '暫停掃描',
    pausing: '正在暫停…',
    resume: '繼續掃描',
    scan: '掃描中繼資料',
    validation: {
      required: '請先輸入既有資料夾路徑。',
      validating: '正在驗證資料夾邊界…',
      authorized: '資料夾已授權。在你選擇「掃描中繼資料」前不會掃描任何內容。',
      denied: '無法授權此資料夾。請確認它存在且未受保護。',
      reading: '正在讀取已授權資料夾中的中繼資料…',
      complete: (files, folders) =>
        `掃描完成：${formatIntegerForLocale(files, 'zh-TW')} 個檔案與 ${formatIntegerForLocale(folders, 'zh-TW')} 個資料夾。`,
      paused: (processed, queued) =>
        `掃描已在發現 ${formatIntegerForLocale(queued, 'zh-TW')} 個項目中的 ${formatIntegerForLocale(processed, 'zh-TW')} 個後暫停。`,
      interrupted: '掃描已安全中斷。檢查已授權資料夾後請繼續。',
      stopped: '中繼資料掃描已安全停止。既有清單資料未被部分取代。',
      creating: '正在建立可持久化的本機掃描工作…',
      startDenied: '無法開始新的掃描。若此資料夾已有工作，請繼續該工作。',
      waiting: '正在等待目前中繼資料項目完成…',
      pauseDenied: '無法安全記錄暫停要求。',
      revalidating: '正在重新驗證已授權資料夾邊界…',
      resumeDenied: '繼續操作被拒絕，因為工作或已授權資料夾不再有效。',
    },
    status: {
      pausing: '正在安全暫停…',
      scanning: '正在掃描中繼資料…',
      paused: '已暫停',
      interrupted: '已安全中斷',
      completed: '已完成',
      stopped: '因錯誤停止',
    },
  },
  footer: {
    version: (version) => `DeskGraph ${version}`,
    description: '中繼資料 + 受限本機文字 · 不上傳 · 不進行檔案操作',
  },
} satisfies Catalog;
